version: '2.1'
services:
  api:
    container_name: my-resume2-api
    image: colus3/my-resume2-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env_local
    ports:
      - 8080:8080
    external_links:
      - my-resume2-db:db
    environment:
      - TZ=Asia/Seoul
networks:
  default:
    external:
      name: my-resume2