version: '2.1'
services:
  api:
    container_name: my-resume2-api
    image: colus3/my-resume2-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul