spring:
  datasource:
    url: jdbc:mysql://db:3306/my_resume_v2?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: qweiop
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false # MySQL auto_increment 사용
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: info

server:
  port: 8080
#    org.hibernate.type: trace

token:
  expiration_time: 30

cookie:
  domain: 'programmeris.me'
  http_only: false
  secure: false